name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r docker-reqs.txt

    - name: Build docker image
      run: |
        docker build -t app .
    - name: Run compose and test REST endpoints
      run: |
        docker-compose up --detach
        docker exec -it app_server /bin/bash
        curl -G "http://127.0.0.1:5000/columns"
        curl -G --data-urlencode "predictor=Смертей" --data-urlencode "numDays=10" http://127.0.0.1:5000/predict
        docker-compose down